version: "2"
services:
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - ${NGINX_EXTERNAL_INTERNAL_PORTS}
        links:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
    php:
        build: ./docker/php
        links:
            - db
        volumes:
            - ./:/var/www/html
    db:
        image: mysql:5.7
        restart: always
        ports:
            - ${DB_EXTERNAL_INTERNAL_PORTS}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - /var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - ${PHP_MYADMIN_EXTERNAL_INTERNAL_PORTS}
        links:
            - db
